=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/Examen/DTD/videojuegos.dtd
<!ELEMENT coleccion (juego+)>
<!ELEMENT juego (titulo, fecha,desarrolladores,editor?,idiomas,generos,motor,metacritic,plataformas,web)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT desarrolladores (desarrollador+)>
<!ELEMENT desarrollador (#PCDATA)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT idiomas (español, ingles,frances?,aleman?,italiano?,chino?)>
<!ELEMENT español EMPTY>
<!ELEMENT frances EMPTY>
<!ELEMENT aleman EMPTY>
<!ELEMENT italiano EMPTY>
<!ELEMENT ingles EMPTY>
<!ELEMENT chino EMPTY>
<!ELEMENT generos (genero, genero, genero)>
<!ELEMENT genero EMPTY>
<!ELEMENT motor (#PCDATA)>
<!ELEMENT metacritic EMPTY>
<!ELEMENT plataformas (plataforma+)>
<!ELEMENT plataforma EMPTY>
<!ELEMENT web (#PCDATA)>
<!ATTLIST juego ident CDATA #REQUIRED>
<!ATTLIST español interfaz (y|n) #REQUIRED
voces (y|n) #REQUIRED
subt (y|n) #REQUIRED>
<!ATTLIST frances interfaz (y|n) #REQUIRED
voces (y|n) #REQUIRED
subt (y|n) #REQUIRED>
<!ATTLIST aleman interfaz (y|n) #REQUIRED
voces (y|n) #REQUIRED
subt (y|n) #REQUIRED>
<!ATTLIST italiano interfaz (y|n) #REQUIRED
voces (y|n) #REQUIRED
subt (y|n) #REQUIRED>
<!ATTLIST ingles interfaz (y|n) #REQUIRED
voces (y|n) #REQUIRED
subt (y|n) #REQUIRED>
<!ATTLIST chino interfaz (y|n) #REQUIRED
voces (y|n) #REQUIRED
subt (y|n) #REQUIRED>
<!ATTLIST genero nombreG (accion|aventura|rol|simulador|plataformas|puzzle|lucha) #REQUIRED>
<!ATTLIST metacritic nota CDATA #REQUIRED>
<!ATTLIST plataforma nombreP (PC|PS3|PS4|PS5|Xbox360|XboxOne|XboxSeries|Switch|Android|iOS) #REQUIRED>
<!ATTLIST fecha tipo CDATA #FIXED "lanzamiento">

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/LMSGI_SEMI_EX1T_solucion/videojuegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coleccion SYSTEM "dtd/videojuegos.dtd">
<coleccion>
	<juego ident="VJ007">
		<titulo>Bioshock</titulo>
		<fecha tipo="lanzamiento">2007-08-21</fecha>
		<desarrolladores>
			<desarrollador>2K Boston</desarrollador>
			<desarrollador>2K Australia</desarrollador>
		</desarrolladores>
		<editor>2K</editor>
		<idiomas>
			<español interfaz="y" voces="y" subt="y"/>
			<ingles interfaz="y" voces="y" subt="y"/>
			<frances interfaz="y" voces="n" subt="y"/>
			<aleman interfaz="y" voces="y" subt="y"/>
			<italiano interfaz="y" voces="y" subt="y"/>
		</idiomas>
		<generos>
			<genero nombreG="accion"/>
			<genero nombreG="rol"/>
			<genero nombreG="aventura"/>
		</generos>
		<motor>Unreal Engine</motor>
		<metacritic nota="96"/>
		<plataformas>
			<plataforma nombreP="PC"/>
			<plataforma nombreP="PS3"/>
			<plataforma nombreP="PS4"/>
			<plataforma nombreP="Xbox360"/>
			<plataforma nombreP="XboxOne"/>
			<plataforma nombreP="Switch"/>
		</plataformas>
		<web>2k.com/en-US/game/bioshock-the-collection/</web>	
	</juego>
	
	<juego ident="VJ008">
		<titulo>Death Stranding</titulo>
		<fecha tipo="lanzamiento">2019-11-08</fecha>
		<desarrolladores>
			<desarrollador>Kojima Productions</desarrollador>
		</desarrolladores>
		<editor>Sony Interactive Entertainment</editor>
		<idiomas>
			<español interfaz="y" voces="y" subt="y"/>
			<ingles interfaz="y" voces="y" subt="y"/>
			<frances interfaz="y" voces="y" subt="y"/>
			<aleman interfaz="y" voces="y" subt="y"/>
			<italiano interfaz="y" voces="y" subt="y"/>
		</idiomas>
		<generos>
			<genero nombreG="accion"/>
			<genero nombreG="rol"/>
			<genero nombreG="aventura"/>
		</generos>
		<motor>Decima</motor>
		<metacritic nota="85"/>
		<plataformas>
			<plataforma nombreP="PC"/>
			<plataforma nombreP="PS4"/>
		</plataformas>
		<web>https://www.kojimaproductions.jp/en/death-stranding-pc</web>
	</juego>


</coleccion>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/Examen/videojuegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coleccion SYSTEM "DTD/videojuegos.dtd">
<coleccion>
    <juego ident="1">
        <titulo>Dark souls</titulo>
        <fecha>11/12/24</fecha>
        <desarrolladores>
            <desarrollador>
                Hidetaka Miyazaki
            </desarrollador>
            <desarrollador>
                Pablo Perez
            </desarrollador>
        </desarrolladores>
        <editor>
            Fromsoftware
        </editor>
        <idiomas>
            <español interfaz="y" voces="y" subt="y" />
            <ingles interfaz="y" voces="y" subt="y" />
            <frances interfaz="y" voces="n" subt="y" />
            <aleman interfaz="n" voces="n" subt="n" />
        </idiomas>
        <generos>
            <genero nombreG="accion" />
            <genero nombreG="aventura" />
            <genero nombreG="lucha" />
        </generos>
        <motor>
            Unreal engine 3
        </motor>
        <metacritic nota="10" />
        <plataformas>
            <plataforma nombreP="PC" />
            <plataforma nombreP="PS3" />
            <plataforma nombreP="Xbox360" />
        </plataformas>
        <web>
            darksouls.com
        </web>
    </juego>
    <juego ident="2">
        <titulo>League of legends</titulo>
        <fecha>14/06/10</fecha>
        <desarrolladores>
            <desarrollador>
                Juan Rodriguez
            </desarrollador>
        </desarrolladores>
        <idiomas>
            <español interfaz="y" voces="y" subt="y" />
            <ingles interfaz="y" voces="y" subt="y" />
            <aleman interfaz="y" voces="y" subt="y" />
            <italiano interfaz="n" voces="n" subt="n" />
            <chino interfaz="y" voces="n" subt="y" />
        </idiomas>
        <generos>
            <genero nombreG="rol" />
            <genero nombreG="puzzle" />
            <genero nombreG="lucha" />
        </generos>
        <motor>
            Unreal engine 3
        </motor>
        <metacritic nota="10" />
        <plataformas>
            <plataforma nombreP="PC" />
            <plataforma nombreP="Android" />
        </plataformas>
        <web>
            lol.com
        </web>
    </juego>
</coleccion>
