=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/3.2/XSD/cartelera.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cartelera">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="titulo_original" type="xs:string" minOccurs="0" />
                            <xs:element name="pais" type="xs:string" />
                            <xs:element name="generos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="genero" type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="clasificacion">
                                    <xs:complexType>
                                        <xs:attribute name="edad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="tp" />
                                                    <xs:enumeration value="7" />
                                                    <xs:enumeration value="12" />
                                                    <xs:enumeration value="16" />
                                                    <xs:enumeration value="18" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="sin_clasificar" />
                            </xs:choice>
                            <xs:element name="sinopsis" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="reparto">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded" minOccurs="1">
                                        <xs:element name="actor" type="xs:string" />
                                        <xs:element name="actriz" type="xs:string" />
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="web" type="xs:anyURI" minOccurs="0" />
                            <xs:element name="cartel" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string" use="required" />
                        <xs:attribute name="duracion" type="xs:integer" use="required" />
                        <xs:attribute name="aÃ±o">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1900" />
                                    <xs:maxInclusive value="2100" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/3.2/cartelera.xml
<?xml version="1.0" encoding="UTF-8"?>
<cartelera xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/cartelera.xsd">
  <pelicula codigo="p1" duracion="130">
    <titulo>SONIC 3: La película</titulo>
    <titulo_original>Sonic the Hedgehog 3</titulo_original>
    <pais>Estados Unidos</pais>
    <generos>
      <genero>Animación</genero>
      <genero>Comedia</genero>
      <genero>Aventura</genero>
    </generos>
    <clasificacion edad="tp" />
    <sinopsis>Sonic, Tails y Knuckles se enfrentarán al Dr. Robotnik antes de que conquiste el mundo. Robotnik tendrá un nuevo aliado: Shadow.</sinopsis>
    <direccion>Jeff Fowler</direccion>
    <reparto>
      <actor>James Marsden</actor>
      <actor>Jim Carrey</actor>
      <actor>Ben Schwartz</actor>
      <actriz>Colleen O'Shaughnessey</actriz>
      <actor>Idris Elba</actor>
      <actor>Keanu Reeves</actor>
    </reparto>
    <web>https://www.sonicthehedgehogmovie.com</web>
    <cartel>caratulas/sonic3.jpg</cartel>
  </pelicula>
  <pelicula codigo="p17" duracion="100" año="2024">
    <titulo>La infiltrada</titulo>
    <pais>España</pais>
    <generos>
      <genero>Suspense</genero>
    </generos>
    <sin_clasificar />
    <sinopsis>Con solo 20 años, Aránzazu logró unirse a la banda ETA, convirtiéndose en la única mujer en compartir un piso con los líderes de la banda. Gracias a dicha infiltración, la Policía Nacional pudo desmantelar el comando Donosti.</sinopsis>
    <direccion>Atrantxa Echevarría</direccion>
    <reparto>
      <actor>Luis Tosar</actor>
      <actriz>Carolina Yuste</actriz>
      <actor>Pedro Casablanc</actor>
      <actor>Víctor Clavijo</actor>
    </reparto>
  </pelicula>
</cartelera>
