=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/3/1.dtd
<!ELEMENT recipes (recipe+)>
<!ELEMENT recipe (name, ingredients, instructions)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT ingredients (ingredient+)>
<!ELEMENT ingredient (#PCDATA)>
<!ELEMENT instructions (#PCDATA)>
<!ATTLIST recipe servings CDATA #REQUIRED>
<!ATTLIST recipe difficulty (low | medium | high) "medium">
<!ATTLIST ingredient quantity CDATA #IMPLIED>
<!ATTLIST ingredient measuring_unit CDATA #IMPLIED>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/3/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipes SYSTEM "1.dtd">
<recipes>
    <recipe servings="1" >
        <name>Pan con ajo y perejil</name>
        <ingredients>
            <ingredient quantity="3">pan</ingredient>
            <ingredient>ajo</ingredient>
            <ingredient quantity="2" measuring_unit="grams">perejil</ingredient>
        </ingredients>
        <instructions>
            Cortar el pan en rebanadas; tostarlo; pelar el ajo; fortarlo en el pan; trocear el perejil; espolvorear sobre el pan
        </instructions>
    </recipe>
</recipes>
