=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/LMSGI_SEMI_EX1T_solucion/xsd/carreras.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="carreras">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="caballo" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element ref="actuaciones"/>
            </xs:sequence>
            <xs:attribute name="porcentaje_victorias" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:nonNegativeInteger">
                  <xs:maxInclusive value="100"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--SEPARADOR-->
  <xs:element name="actuaciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="actuacion" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--SEPARADOR-->
  <xs:element name="actuacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="num" type="xs:positiveInteger"/>
        <xs:element name="hipodromo" type="xs:string"/>
        <xs:element name="distancia">
          <xs:complexType>
            <xs:attribute name="km" type="tipoKm" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="dotacion" type="xs:positiveInteger"/>
        <xs:element ref="pista"/>
        <xs:element ref="jinete"/>
        <xs:element name="preparador" type="xs:string"/>
        <xs:choice>
          <xs:element name="div" type="xs:decimal"/>
          <xs:element name="ganancia" type="xs:positiveInteger"/>
        </xs:choice>
        <xs:element name="puesto">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:positiveInteger">
                <xs:attribute name="participantes" type="xs:positiveInteger" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--SEPARADOR-->
  <xs:simpleType name="tipoKm">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <!--SEPARADOR-->
  <xs:element name="pista">
    <xs:complexType>
      <xs:attribute name="tipo" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="arena"/>
            <xs:enumeration value="hierba"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="caract">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="blando"/>
            <xs:enumeration value="bueno"/>
            <xs:enumeration value="duro"/>
            <xs:enumeration value="pesado"/>
            <xs:enumeration value="embarrado"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <!--SEPARADOR-->
  <xs:element name="jinete">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="peso" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/LMSGI_SEMI_EX1T_solucion/carreras.xml
<?xml version="1.0" encoding="UTF-8"?>
<carreras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/carreras.xsd">
  <caballo porcentaje_victorias="20">
    <nombre>Bailarina</nombre>
    <actuaciones>
      <actuacion>
        <fecha>2011-11-13</fecha>
        <num>517</num>
        <hipodromo>La Zarzuela</hipodromo>
        <distancia km="2.2"/>
        <dotacion>4000</dotacion>
        <pista tipo="hierba" caract="blando"/>
        <jinete>
          <nombre>E. Melian</nombre>
          <peso>59</peso>
        </jinete>
        <preparador>G. Arizcorreta</preparador>
        <div>9.0</div>
        <puesto participantes="15">10</puesto>
      </actuacion>
      <actuacion>
        <fecha>2011-11-01</fecha>
        <num>496</num>
        <hipodromo>Pineda</hipodromo>
        <distancia km="1.6"/>
        <dotacion>4000</dotacion>
        <pista tipo="arena"/>
        <jinete>
          <nombre>E. Melian</nombre>
          <peso>53.5</peso>
        </jinete>
        <preparador>G. Arizcorreta</preparador>
        <ganancia>4000</ganancia>
        <puesto participantes="6">1</puesto>
      </actuacion>
      <actuacion>
        <fecha>2011-10-02</fecha>
        <num>450</num>
        <hipodromo>La Zarzuela</hipodromo>
        <distancia km="2.1"/>
        <dotacion>4500</dotacion>
        <pista tipo="hierba" caract="bueno"/>
        <jinete>
          <nombre>E. Melian</nombre>
          <peso>53.5</peso>
        </jinete>
        <preparador>G. Arizcorreta</preparador>
        <div>12.6</div>
        <puesto participantes="9">6</puesto>
      </actuacion>
      <actuacion>
        <fecha>2011-09-01</fecha>
        <num>405</num>
        <hipodromo>Lasarte</hipodromo>
        <distancia km="1.6"/>
        <dotacion>4500</dotacion>
        <pista tipo="hierba" caract="bueno"/>
        <jinete>
          <nombre>E. Melian</nombre>
          <peso>54.5</peso>
        </jinete>
        <preparador>G. Arizcorreta</preparador>
        <div>21.0</div>
        <puesto participantes="7">6</puesto>
      </actuacion>
      <actuacion>
        <fecha>2011-04-11</fecha>
        <num>138</num>
        <hipodromo>La Zarzuela</hipodromo>
        <distancia km="1.8"/>
        <dotacion>5000</dotacion>
        <pista tipo="hierba" caract="pesado"/>
        <jinete>
          <nombre>J.L. Borrego</nombre>
          <peso>57.5</peso>
        </jinete>
        <preparador>G. Arizcorreta</preparador>
        <div>25.6</div>
        <puesto participantes="12">11</puesto>
      </actuacion>
    </actuaciones>
  </caballo>
</carreras>
