=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/LMSGI_SEMI_EX1T_solucion/dtd/placas.dtd
<!ELEMENT placasbase (placa+)>
  <!ELEMENT placa (marca, modelo, socket, chipset, memoria, puertosGraficos, expansion, almacenamiento, USB)>
  <!ELEMENT marca (#PCDATA)>
  <!ELEMENT modelo (#PCDATA)>
  <!ELEMENT socket (#PCDATA)>
  <!ELEMENT chipset (#PCDATA)>
  <!ELEMENT memoria (tipoMemoria, slots, maxMemoria)>
    <!ELEMENT tipoMemoria (#PCDATA)>
    <!ELEMENT slots (#PCDATA)>
    <!ELEMENT maxMemoria (#PCDATA)>
  <!ELEMENT puertosGraficos (puerto+)>
    <!ELEMENT puerto (#PCDATA)>
  <!ELEMENT expansion (ranura+)>
    <!ELEMENT ranura (cantidad, longitud)>
      <!ELEMENT cantidad (#PCDATA)>
      <!ELEMENT longitud (#PCDATA)>
  <!ELEMENT almacenamiento (SATA, M.2?)>
  <!ELEMENT SATA (#PCDATA)>
  <!ELEMENT M.2 (#PCDATA)>
  <!ELEMENT USB (trasero, frontal)> 
    <!ELEMENT trasero (v3.2+, v2.0+)>
    <!ELEMENT frontal (v3.2+, v2.0+)>
      <!ELEMENT v3.2 EMPTY>
      <!ELEMENT v2.0 EMPTY>
  <!ATTLIST socket fabricante (AMD|INTEL) #REQUIRED>
  <!ATTLIST memoria tipoModulo CDATA #FIXED "DIMM">
  <!ATTLIST maxMemoria unidad CDATA "GB">
  <!ATTLIST puerto tipo CDATA #REQUIRED>
  <!ATTLIST ranura bus CDATA #REQUIRED>
  <!ATTLIST v3.2 gen CDATA #REQUIRED
  tipo (A|B|C) #IMPLIED
  cantidad CDATA #REQUIRED>
  <!ATTLIST v2.0 tipo (A|B) #IMPLIED
  cantidad CDATA #REQUIRED>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/LMSGI_SEMI_EX1T_solucion/placas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE placasbase SYSTEM "dtd/placas.dtd">
<placasbase>
  <placa>
    <marca>ASUS</marca>
    <modelo>TUF GAMING B650-PLUS WIFI</modelo>
    <socket fabricante="AMD">AM5</socket>
    <chipset>AMD B650</chipset>
    <memoria tipoModulo="DIMM">
      <tipoMemoria>DDR5</tipoMemoria>
      <slots>4</slots>
      <maxMemoria>128</maxMemoria>
    </memoria>
    <puertosGraficos>
      <puerto tipo="DisplayPort">1</puerto>
      <puerto tipo="HDMI">1</puerto>
    </puertosGraficos>
    <expansion>
      <ranura bus="PCIe 4.0/3.0">
        <cantidad>1</cantidad>
        <longitud>x16</longitud>
      </ranura>
      <ranura bus="PCIe 4.0/3.0">
        <cantidad>1</cantidad>
        <longitud>x4</longitud>
      </ranura>
      <ranura bus="PCIe 4.0/3.0">
        <cantidad>2</cantidad>
        <longitud>x1</longitud>
      </ranura>
    </expansion>
    <almacenamiento>
      <SATA>4</SATA>
      <M.2>3</M.2>
    </almacenamiento>
    <USB>
      <trasero>
        <v3.2 gen="2" tipo="A" cantidad="1"/>
        <v3.2 gen="1" tipo="A" cantidad="4"/>
        <v3.2 gen="2" tipo="C" cantidad="1"/>
        <v2.0 tipo="A" cantidad="2"/>
      </trasero>
      <frontal>
        <v3.2 gen="1" cantidad="1"/>
        <v3.2 gen="2" cantidad="1"/>
        <v2.0 cantidad="2"/>
      </frontal>
    </USB>
  </placa>
  <placa>
    <marca>ASUS</marca>
    <modelo>ROG STRIX B550-F GAMING WIFI II</modelo>
    <socket fabricante="AMD">AM4</socket>
    <chipset>AMD B550</chipset>
    <memoria tipoModulo="DIMM">
      <tipoMemoria>DDR4</tipoMemoria>
      <slots>4</slots>
      <maxMemoria unidad="GB">128</maxMemoria>
    </memoria>
    <puertosGraficos>
      <puerto tipo="DisplayPort">1</puerto>
      <puerto tipo="HDMI">1</puerto>
    </puertosGraficos>
    <expansion>
      <ranura bus="PCIe 4.0/3.0">
        <cantidad>1</cantidad>
        <longitud>x16</longitud>
      </ranura>
      <ranura bus="PCIe 4.0/3.0">
        <cantidad>1</cantidad>
        <longitud>x4</longitud>
      </ranura>
      <ranura bus="PCIe 4.0/3.0">
        <cantidad>3</cantidad>
        <longitud>x1</longitud>
      </ranura>
    </expansion>
    <almacenamiento>
      <SATA>6</SATA>
      <M.2>2</M.2>
    </almacenamiento>
    <USB>
      <trasero>
        <v3.2 gen="2x2" tipo="C" cantidad="1"/>
        <v3.2 gen="2" tipo="A" cantidad="2"/>
        <v3.2 gen="2" tipo="C" cantidad="1"/>
        <v2.0 tipo="A" cantidad="4"/>
      </trasero>
      <frontal>
        <v3.2 gen="1" cantidad="3"/>
        <v2.0 cantidad="4"/>
      </frontal>
    </USB>
  </placa>
</placasbase>
