=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/Examen/XSD/pinturas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pinturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pintura" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                           <xs:element name="titulo"  maxOccurs="1" >
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="original" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                           </xs:element>
                           <xs:element name="alias" type="xs:string" minOccurs="0" maxOccurs="1" />
                           <xs:element name="autor" type="xs:string"  maxOccurs="1" />
                           <xs:element name="aÃ±o" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:maxExclusive value="2100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                           </xs:element>
                           <xs:element name="tecnicas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tecnica" type="xs:string"  minOccurs="1" maxOccurs="4"/>
                                    </xs:sequence>
                                </xs:complexType>
                           </xs:element>
                            <xs:element name="estilo" type="xs:string"  maxOccurs="1" />
                            <xs:choice>
                                <xs:element name="localizacion">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="nombre" type="xs:string"  maxOccurs="1" />
                                        <xs:element name="ciudad" type="xs:string"  maxOccurs="1" />
                                    </xs:all>
                                </xs:complexType>
                                </xs:element>
                                <xs:element name="paradero_desconocido" default="">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:length value="0" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                            </xs:choice>
                           <xs:element name="precio"  maxOccurs="1" >
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:int">
                                            <xs:attribute name="moneda" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:length value="3"></xs:length>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                           </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/Examen/pinturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<pinturas xsi:noNamespaceSchemaLocation="XSD/pinturas.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <pintura>
    <titulo original="Marilyn Diptych">Díptico de Marilyn</titulo>
    <autor>Andy Warhol</autor>
    <año>1962</año>
    <tecnicas>
      <tecnica>Serigrafía</tecnica>
      <tecnica>Pintura acrílica sobre lienzo</tecnica>
    </tecnicas>
    <estilo>Arte pop</estilo>
    <localizacion>
      <nombre>Tate</nombre>
      <ciudad>Londres</ciudad>
    </localizacion>
    <precio moneda="USD">860000</precio>
  </pintura>
  <pintura>
    <titulo original="Le pigeon aux petits pois">La paloma con guisantes</titulo>
    <alias>La paloma con guisantes verdes</alias>
    <autor>Pablo Picasso</autor>
    <año>1912</año>
    <tecnicas>
      <tecnica>Óleo sobre lienzo</tecnica>
    </tecnicas>
    <estilo>Cubismo</estilo>
    <paradero_desconocido/>
    <precio moneda="EUR">27000000</precio>
  </pintura>
  <pintura>
    <titulo original="Stjernenatten">La noche estrellada</titulo>
    <autor>Vincent van Gogh</autor>
    <año>1889</año>
    <tecnicas>
      <tecnica>Óleo sobre lienzo</tecnica>
    </tecnicas>
    <estilo>Posimpresionismo</estilo>
    <localizacion>
      <nombre>MoMA</nombre>
      <ciudad>Nueva York</ciudad>
    </localizacion>
    <precio moneda="USD">100000000</precio>
  </pintura>
</pinturas>
