=== LopezJuanIgnacio/FP-1ro-LMSGI/3.2/XSD/canciones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="canciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cancion" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="titulo" type="xs:string" maxOccurs="1"/>
                            <xs:element name="compositores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="compositor" maxOccurs="unbounded"
                                            minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string" />
                                                    <xs:element name="apellidos" type="xs:string"
                                                        minOccurs="0" maxOccurs="1" />
                                                </xs:sequence>
                                            </xs:complexType>
                                            <xs:unique name="uniqueApellidos">
                                                <xs:selector xpath="compositor" />
                                                <xs:field xpath="apellidos" />
                                            </xs:unique>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="disco" type="xs:string" />
                            <xs:element name="sello" type="xs:string" />
                            <xs:element name="artistas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="artista" type="xs:string"
                                            maxOccurs="unbounded" minOccurs="1" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="duracion" type="xs:positiveInteger" use="optional" />
                        <xs:attribute name="aÃ±o" type="xs:gYear" use="required" />
                    </xs:complexType>
                    <xs:unique name="uniqueTitulo">
                        <xs:selector xpath="cancion" />
                        <xs:field xpath="titulo" />
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LopezJuanIgnacio/FP-1ro-LMSGI/3.2/canciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<canciones xsi:noNamespaceSchemaLocation="XSD/canciones.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <cancion duracion="4:08" año="1979">
    <titulo>Video Killed the Radio Star</titulo>
    <compositores>
      <compositor>
        <nombre>Geoff</nombre>
        <apellidos>Downes</apellidos>
      </compositor>
      <compositor>
        <nombre>Trevor</nombre>
        <apellidos>Horn</apellidos>
      </compositor>
      <compositor>
        <nombre>Bruce</nombre>
        <apellidos>Woolley</apellidos>
      </compositor>
    </compositores>
    <disco>The Age of Plastic</disco>
    <sello>Island</sello>
    <artistas>
      <artista>Buggles</artista>
    </artistas>
  </cancion>
</canciones>
