=== LopezJuanIgnacio/FP-1ro-LMSGI/3.2/XSD/ventas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ventas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cabecera">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="subtitulo" type="xs:string" />
                            <xs:element name="descripcion" type="xs:string" />
                            <xs:element name="fecha" type="xs:string" minOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cuerpo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="norte" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="libros_vendidos" minOccurs="4"
                                            maxOccurs="4">
                                            <xs:complexType>
                                                <xs:attribute name="trimestre">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1" />
                                                            <xs:maxInclusive value="4" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="unidades" default="-1">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="-1" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="centro" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="libros_vendidos" minOccurs="4"
                                            maxOccurs="4">
                                            <xs:complexType>
                                                <xs:attribute name="trimestre">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1" />
                                                            <xs:maxInclusive value="4" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="unidades" default="-1">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="-1" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sur" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="libros_vendidos" minOccurs="4"
                                            maxOccurs="4">
                                            <xs:complexType>
                                                <xs:attribute name="trimestre">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1" />
                                                            <xs:maxInclusive value="4" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="unidades" default="-1">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="-1" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/3.2/ventas.xml
<?xml version="1.0" encoding="UTF-8"?>
<ventas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD/ventas.xsd">
  <cabecera>
    <nombre>Ediciones Aranda</nombre>
    <subtitulo>Informe regional de ventas</subtitulo>
    <descripcion>informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>30/12/2009</fecha>
  </cabecera>
  <cuerpo>
    <norte>
      <libros_vendidos trimestre="1" unidades="24000"/>
      <libros_vendidos trimestre="2" unidades="38600"/>
      <libros_vendidos trimestre="3"/>
      <libros_vendidos trimestre="4"/>
    </norte>
    <centro>
      <libros_vendidos trimestre="1"/>
      <libros_vendidos trimestre="2" unidades="16080"/>
      <libros_vendidos trimestre="3" unidades="25000"/>
      <libros_vendidos trimestre="4" unidades="29000"/>
    </centro>
    <sur>
      <libros_vendidos trimestre="1" unidades="27000"/>
      <libros_vendidos trimestre="2" unidades="31400"/>
      <libros_vendidos trimestre="3" unidades="40100"/>
      <libros_vendidos trimestre="4" unidades="30000"/>
    </sur>
  </cuerpo>
</ventas>
