=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/XSD examples/receta_x_local.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="recetas"><!--APERTURA ELEMENTO RAÍZ-->
    <xs:complexType>
      <xs:sequence>
        <xs:element name="receta" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="ingredientes"><!--ELEMENTO <ingredientes>-->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ingrediente" maxOccurs="unbounded">
                      <xs:complexType><!--CONTIENE TEXTO Y ATRIBUTOS-->
                        <xs:simpleContent>
                          <xs:extension base="xs:string"><!--TIPO SIMPLE DEL "TEXTO CONTENIDO"-->
                            <xs:attribute name="cantidad" type="xs:decimal"/><!--TIPO SIMPLE DE ESTE ATRIBUTO-->
                            <xs:attribute name="unidad" type="xs:string"/><!--TIPO SIMPLE DE ESTE ATRIBUTO-->
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="preparacion" type="xs:string"/>
            </xs:sequence><!--ATRIBUTOS SIEMPRE DESPUÉS DE ELEMENTOS (de <receta>)-->
            <xs:attribute name="numRaciones"  type="xs:positiveInteger"/>
             <xs:attribute name="dificultad" default="media">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="baja"/>
                  <xs:enumeration value="media"/>
                  <xs:enumeration value="alta"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element><!--CIERRE ELEMENTO RAÍZ -->
</xs:schema><!--CIERRE DEL ESQUEMA-->

=== LopezJuanIgnacio/FP-1ro-LMSGI/XSD examples/receta_x_local.xml
<?xml version="1.0" encoding="UTF-8"?>
<recetas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="receta_x_local.xsd">
  <receta numRaciones="1" >
    <nombre>Pan con ajo y perejil</nombre>
    <ingredientes>
      <ingrediente>Pan</ingrediente>
      <ingrediente>Ajo</ingrediente>
      <ingrediente cantidad="1" unidad="puñao">Perejil</ingrediente>
    </ingredientes>
    <preparacion>Cortar el pan en rebanadas; tostarlo; pelar el ajo; fortarlo en el pan; trocear el perejil; espolvorear sobre el pan</preparacion>
  </receta>
</recetas>
