=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/3.1/DTD/1.dtd
<!-- En el esquema DTD no se le puede poner restricciones al (#PCDATA), eso se puede en el XSD
Asique lo deje como un atributo ID -->
<!ELEMENT canciones (cancion+) >
<!ELEMENT cancion (titulo, compositores, disco, sello, artistas) >
<!ATTLIST cancion 
    duracion CDATA #IMPLIED
    aÃ±o CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT compositores (compositor+) >
<!ELEMENT compositor (nombre, apellidos?) >
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT disco (#PCDATA)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artistas (artista+) >
<!ELEMENT artista (#PCDATA)>

=== LopezJuanIgnacio/FP-1ro-LMSGI/Primer trimestre/3.1/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE canciones SYSTEM "DTD/1.dtd">
<canciones>
  <cancion duracion="4:08" año="1979">
    <titulo>Video Killed the Radio Star</titulo>
    <compositores>
      <compositor>
        <nombre>Geoff</nombre>
        <apellidos>Downes</apellidos>
      </compositor>
      <compositor>
        <nombre>Trevor</nombre>
        <apellidos>Horn</apellidos>
      </compositor>
      <compositor>
        <nombre>Bruce</nombre>
        <apellidos>Woolley</apellidos>
      </compositor>
    </compositores>
    <disco>The Age of Plastic</disco>
    <sello>Island</sello>
    <artistas>
      <artista>Buggles</artista>
    </artistas>
  </cancion>
</canciones>
